/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Fechamento;
import ModelDao.FechamentoDAO;
import java.text.DecimalFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lucas
 */
public class FrameTwo extends javax.swing.JFrame {
    float aprazo,recebido,saida,cartao,caixaAtual,caixaAnterior,vendas,sobra;
    int v1=1,v2=1,v3=1,v4=1,v5=1,v6=1,v7=1;
    

    /**
     * Creates new form FrameTwo
     */
    public FrameTwo() {
        initComponents();
        readJTable();
        setSize(1150,650);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtAprazo = new javax.swing.JTextField();
        lblAprazo = new javax.swing.JLabel();
        txtRecebido = new javax.swing.JTextField();
        lblRecebido = new javax.swing.JLabel();
        txtSaida = new javax.swing.JTextField();
        lblSaida = new javax.swing.JLabel();
        txtCartao = new javax.swing.JTextField();
        lblCartao = new javax.swing.JLabel();
        txtCaixaAtual = new javax.swing.JTextField();
        lblCaixaAtual = new javax.swing.JLabel();
        txtCaixaAnterior = new javax.swing.JTextField();
        lblCaixaAnterior = new javax.swing.JLabel();
        txtVendas = new javax.swing.JTextField();
        lblVendas = new javax.swing.JLabel();
        lblSobra = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbFrameTwo = new javax.swing.JTable();
        btnApView = new javax.swing.JButton();
        btnApFechado = new javax.swing.JButton();
        btnRecFechado = new javax.swing.JButton();
        btnRecView = new javax.swing.JButton();
        btnSaiFechado = new javax.swing.JButton();
        btnSaiView = new javax.swing.JButton();
        btnCarFechado = new javax.swing.JButton();
        btnCarView = new javax.swing.JButton();
        btnCAtFechado = new javax.swing.JButton();
        btnCAtView = new javax.swing.JButton();
        btnCRtFechado = new javax.swing.JButton();
        btnCRtView = new javax.swing.JButton();
        btnVenFechado = new javax.swing.JButton();
        btnVenView = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(61, 91, 129));
        jPanel1.setForeground(new java.awt.Color(61, 91, 129));
        jPanel1.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconeCalc.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 440, 170);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 1120, 170);

        txtAprazo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtAprazo.setText("00");
        txtAprazo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAprazoActionPerformed(evt);
            }
        });
        getContentPane().add(txtAprazo);
        txtAprazo.setBounds(40, 220, 240, 30);

        lblAprazo.setBackground(new java.awt.Color(61, 91, 129));
        lblAprazo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblAprazo.setForeground(new java.awt.Color(61, 91, 129));
        lblAprazo.setText("A PRAZO:");
        getContentPane().add(lblAprazo);
        lblAprazo.setBounds(40, 200, 90, 20);

        txtRecebido.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtRecebido.setText("00");
        getContentPane().add(txtRecebido);
        txtRecebido.setBounds(40, 280, 240, 30);

        lblRecebido.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblRecebido.setForeground(new java.awt.Color(61, 91, 129));
        lblRecebido.setText("RECEBIDO:");
        getContentPane().add(lblRecebido);
        lblRecebido.setBounds(40, 260, 120, 20);

        txtSaida.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtSaida.setText("00");
        getContentPane().add(txtSaida);
        txtSaida.setBounds(40, 340, 240, 30);

        lblSaida.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblSaida.setForeground(new java.awt.Color(61, 91, 129));
        lblSaida.setText("SAIDA:");
        getContentPane().add(lblSaida);
        lblSaida.setBounds(40, 320, 90, 20);

        txtCartao.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtCartao.setText("00");
        getContentPane().add(txtCartao);
        txtCartao.setBounds(40, 400, 240, 30);

        lblCartao.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblCartao.setForeground(new java.awt.Color(61, 91, 129));
        lblCartao.setText("CARTÃO:");
        getContentPane().add(lblCartao);
        lblCartao.setBounds(40, 380, 90, 20);

        txtCaixaAtual.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtCaixaAtual.setText("00");
        getContentPane().add(txtCaixaAtual);
        txtCaixaAtual.setBounds(40, 460, 240, 30);

        lblCaixaAtual.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblCaixaAtual.setForeground(new java.awt.Color(61, 91, 129));
        lblCaixaAtual.setText("CAIXA ATUAL:");
        getContentPane().add(lblCaixaAtual);
        lblCaixaAtual.setBounds(40, 440, 140, 20);

        txtCaixaAnterior.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtCaixaAnterior.setText("00");
        getContentPane().add(txtCaixaAnterior);
        txtCaixaAnterior.setBounds(40, 520, 240, 30);

        lblCaixaAnterior.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblCaixaAnterior.setForeground(new java.awt.Color(61, 91, 129));
        lblCaixaAnterior.setText("CAIXA ANTERIOR:");
        getContentPane().add(lblCaixaAnterior);
        lblCaixaAnterior.setBounds(40, 500, 170, 20);

        txtVendas.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtVendas.setText("00");
        getContentPane().add(txtVendas);
        txtVendas.setBounds(40, 580, 240, 30);

        lblVendas.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblVendas.setForeground(new java.awt.Color(61, 91, 129));
        lblVendas.setText("VENDAS:");
        getContentPane().add(lblVendas);
        lblVendas.setBounds(40, 560, 90, 20);

        lblSobra.setFont(new java.awt.Font("Dialog", 1, 60)); // NOI18N
        lblSobra.setText("00");
        getContentPane().add(lblSobra);
        lblSobra.setBounds(460, 300, 290, 150);

        btnCalcular.setBackground(new java.awt.Color(61, 91, 129));
        btnCalcular.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnCalcular.setForeground(new java.awt.Color(255, 255, 255));
        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalcular);
        btnCalcular.setBounds(480, 550, 180, 50);

        btnSalvar.setBackground(new java.awt.Color(102, 255, 102));
        btnSalvar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvar.setText("Salvar");
        btnSalvar.setToolTipText("");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar);
        btnSalvar.setBounds(680, 550, 180, 50);

        jtbFrameTwo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jtbFrameTwo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "DATA", "SOBRA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtbFrameTwo);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(760, 200, 370, 340);

        btnApView.setBackground(new java.awt.Color(61, 91, 129));
        btnApView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Sem Título-2.png"))); // NOI18N
        btnApView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApViewActionPerformed(evt);
            }
        });
        getContentPane().add(btnApView);
        btnApView.setBounds(350, 220, 50, 30);

        btnApFechado.setBackground(new java.awt.Color(61, 91, 129));
        btnApFechado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconOlhoFechado.png"))); // NOI18N
        btnApFechado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApFechadoActionPerformed(evt);
            }
        });
        getContentPane().add(btnApFechado);
        btnApFechado.setBounds(290, 220, 50, 30);

        btnRecFechado.setBackground(new java.awt.Color(61, 91, 129));
        btnRecFechado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconOlhoFechado.png"))); // NOI18N
        btnRecFechado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecFechadoActionPerformed(evt);
            }
        });
        getContentPane().add(btnRecFechado);
        btnRecFechado.setBounds(290, 280, 50, 30);

        btnRecView.setBackground(new java.awt.Color(61, 91, 129));
        btnRecView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Sem Título-2.png"))); // NOI18N
        btnRecView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecViewActionPerformed(evt);
            }
        });
        getContentPane().add(btnRecView);
        btnRecView.setBounds(350, 280, 50, 30);

        btnSaiFechado.setBackground(new java.awt.Color(61, 91, 129));
        btnSaiFechado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconOlhoFechado.png"))); // NOI18N
        btnSaiFechado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaiFechadoActionPerformed(evt);
            }
        });
        getContentPane().add(btnSaiFechado);
        btnSaiFechado.setBounds(290, 340, 50, 30);

        btnSaiView.setBackground(new java.awt.Color(61, 91, 129));
        btnSaiView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Sem Título-2.png"))); // NOI18N
        btnSaiView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaiViewActionPerformed(evt);
            }
        });
        getContentPane().add(btnSaiView);
        btnSaiView.setBounds(350, 340, 50, 30);

        btnCarFechado.setBackground(new java.awt.Color(61, 91, 129));
        btnCarFechado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconOlhoFechado.png"))); // NOI18N
        btnCarFechado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarFechadoActionPerformed(evt);
            }
        });
        getContentPane().add(btnCarFechado);
        btnCarFechado.setBounds(290, 400, 50, 30);

        btnCarView.setBackground(new java.awt.Color(61, 91, 129));
        btnCarView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Sem Título-2.png"))); // NOI18N
        btnCarView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarViewActionPerformed(evt);
            }
        });
        getContentPane().add(btnCarView);
        btnCarView.setBounds(350, 400, 50, 30);

        btnCAtFechado.setBackground(new java.awt.Color(61, 91, 129));
        btnCAtFechado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconOlhoFechado.png"))); // NOI18N
        btnCAtFechado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCAtFechadoActionPerformed(evt);
            }
        });
        getContentPane().add(btnCAtFechado);
        btnCAtFechado.setBounds(290, 460, 50, 30);

        btnCAtView.setBackground(new java.awt.Color(61, 91, 129));
        btnCAtView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Sem Título-2.png"))); // NOI18N
        btnCAtView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCAtViewActionPerformed(evt);
            }
        });
        getContentPane().add(btnCAtView);
        btnCAtView.setBounds(350, 460, 50, 30);

        btnCRtFechado.setBackground(new java.awt.Color(61, 91, 129));
        btnCRtFechado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconOlhoFechado.png"))); // NOI18N
        btnCRtFechado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCRtFechadoActionPerformed(evt);
            }
        });
        getContentPane().add(btnCRtFechado);
        btnCRtFechado.setBounds(290, 520, 50, 30);

        btnCRtView.setBackground(new java.awt.Color(61, 91, 129));
        btnCRtView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Sem Título-2.png"))); // NOI18N
        btnCRtView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCRtViewActionPerformed(evt);
            }
        });
        getContentPane().add(btnCRtView);
        btnCRtView.setBounds(350, 520, 50, 30);

        btnVenFechado.setBackground(new java.awt.Color(61, 91, 129));
        btnVenFechado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconOlhoFechado.png"))); // NOI18N
        btnVenFechado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVenFechadoActionPerformed(evt);
            }
        });
        getContentPane().add(btnVenFechado);
        btnVenFechado.setBounds(290, 580, 50, 30);

        btnVenView.setBackground(new java.awt.Color(61, 91, 129));
        btnVenView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Sem Título-2.png"))); // NOI18N
        btnVenView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVenViewActionPerformed(evt);
            }
        });
        getContentPane().add(btnVenView);
        btnVenView.setBounds(350, 580, 50, 30);

        btnExcluir.setBackground(new java.awt.Color(255, 102, 102));
        btnExcluir.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnExcluir.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluir.setText("Excluir");
        btnExcluir.setToolTipText("");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcluir);
        btnExcluir.setBounds(880, 550, 180, 50);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/background df.png"))); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(-6, -6, 1160, 660);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
        DecimalFormat df =  new DecimalFormat("0.00");
        if(v1==1){
            aprazo = Float.parseFloat(txtAprazo.getText());
        }
        if(v2==1){
        recebido = Float.parseFloat(txtRecebido.getText());
        }
        if(v3==1){
        saida = Float.parseFloat(txtSaida.getText());
        }
        if(v4==1){
        cartao = Float.parseFloat(txtCartao.getText());
        }
        if(v5==1){
        caixaAtual = Float.parseFloat(txtCaixaAtual.getText());
        }
        if(v6==1){
        caixaAnterior = Float.parseFloat(txtCaixaAnterior.getText());
        }
        if(v7==1){
        vendas = Float.parseFloat(txtVendas.getText());
        }
        
        sobra = (((aprazo+saida+caixaAtual+cartao) - (caixaAnterior + recebido))-vendas);
        if(sobra == vendas){
            JOptionPane.showMessageDialog(null,"Parabéns, todos as Vendas foram lançadas");
            lblSobra.setText(String.valueOf(df.format(sobra)));
        }else{
            JOptionPane.showMessageDialog(null,"Que pena, parece que nem todas as vendas foram lançadas");
            lblSobra.setText(String.valueOf(df.format(sobra)));
        }
        
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void txtAprazoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAprazoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAprazoActionPerformed

    private void btnApViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApViewActionPerformed
        // TODO add your handling code here:
            v1=1;
            txtAprazo.setText(String.valueOf(aprazo));
            
    }//GEN-LAST:event_btnApViewActionPerformed

    private void btnApFechadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApFechadoActionPerformed
        // TODO add your handling code here:
            v1=0;
            aprazo = Float.parseFloat(txtAprazo.getText());
            txtAprazo.setText("*******");
    }//GEN-LAST:event_btnApFechadoActionPerformed

    private void btnRecFechadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecFechadoActionPerformed
        // TODO add your handling code here:
            v2=0;
            recebido = Float.parseFloat(txtRecebido.getText());
            txtRecebido.setText("*******");
    }//GEN-LAST:event_btnRecFechadoActionPerformed

    private void btnRecViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecViewActionPerformed
        // TODO add your handling code here:
        v2=1;
        txtRecebido.setText(String.valueOf(recebido));
    }//GEN-LAST:event_btnRecViewActionPerformed

    private void btnSaiFechadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaiFechadoActionPerformed
        // TODO add your handling code here:
            v3=0;
            saida = Float.parseFloat(txtSaida.getText());
            txtSaida.setText("*******");
    }//GEN-LAST:event_btnSaiFechadoActionPerformed

    private void btnSaiViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaiViewActionPerformed
        // TODO add your handling code here:
        v3=1;
        txtSaida.setText(String.valueOf(saida));
    }//GEN-LAST:event_btnSaiViewActionPerformed

    private void btnCarFechadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarFechadoActionPerformed
        // TODO add your handling code here:
        v4=0;
            cartao = Float.parseFloat(txtCartao.getText());
            txtCartao.setText("*******");
    }//GEN-LAST:event_btnCarFechadoActionPerformed

    private void btnCarViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarViewActionPerformed
        // TODO add your handling code here:
        v4=1;
        txtCartao.setText(String.valueOf(cartao));
    }//GEN-LAST:event_btnCarViewActionPerformed

    private void btnCAtFechadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCAtFechadoActionPerformed
        // TODO add your handling code here:
            v5=0;
            caixaAtual = Float.parseFloat(txtCaixaAtual.getText());
            txtCaixaAtual.setText("*******");
    }//GEN-LAST:event_btnCAtFechadoActionPerformed

    private void btnCAtViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCAtViewActionPerformed
        // TODO add your handling code here:
        v5=1;
        txtCaixaAtual.setText(String.valueOf(caixaAtual));
    }//GEN-LAST:event_btnCAtViewActionPerformed

    private void btnCRtFechadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCRtFechadoActionPerformed
        // TODO add your handling code here:
            v6=0;
            caixaAnterior = Float.parseFloat(txtCaixaAnterior.getText());
            txtCaixaAnterior.setText("*******");
    }//GEN-LAST:event_btnCRtFechadoActionPerformed

    private void btnCRtViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCRtViewActionPerformed
        // TODO add your handling code here:
        v6=1;
        txtCaixaAnterior.setText(String.valueOf(caixaAnterior));
    }//GEN-LAST:event_btnCRtViewActionPerformed

    private void btnVenFechadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenFechadoActionPerformed
        // TODO add your handling code here:
            v7=0;
            vendas = Float.parseFloat(txtVendas.getText());
            txtVendas.setText("*******");
    }//GEN-LAST:event_btnVenFechadoActionPerformed

    private void btnVenViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenViewActionPerformed
        // TODO add your handling code here:
        v7=1;
        txtVendas.setText(String.valueOf(vendas));
    }//GEN-LAST:event_btnVenViewActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        Fechamento f = new Fechamento();
        FechamentoDAO dao = new FechamentoDAO();
        if(sobra!=00){
        
        //inicializando linhas para data
        Date x;
        x = new Date();
        int d,m=1,a;
        d = x.getDate();
        m = x.getMonth();
        a = (x.getYear()+1900);
        if(m>=13){
            m=12;
        }else{
            m++;
        }    

        f.setAprazo(aprazo);
        f.setRecebido(recebido);
        f.setSaida(saida);
        f.setCartao(cartao);
        f.setCaixaAtual(caixaAtual);
        f.setCaixaAnterior(caixaAnterior);
        f.setVenda(vendas);
        f.setSobra(sobra);
        if(m>10){
            if(d<10){
                f.setData("0"+d+"/"+m+"/"+a);
                dao.create(f);
            }else{
                f.setData(d+"/"+m+"/"+a);
                dao.create(f);
            }
        }else{
            if(d<10){
                f.setData("0"+d+"/0"+m+"/"+a);
                dao.create(f);
            }else{
                f.setData(d+"/0"+m+"/"+a);
                dao.create(f);
            }
        }
        }else{
            JOptionPane.showMessageDialog(null, "Faça o calculo primeiro para Salvar");
        }
        readJTable();
            
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        if(jtbFrameTwo.getSelectedRow() != -1){
            Fechamento f = new Fechamento();
            FechamentoDAO dao = new FechamentoDAO();

            f.setId((int) jtbFrameTwo.getValueAt(jtbFrameTwo.getSelectedRow(), 0));

            dao.delete(f);

            readJTable();
        }else{
            JOptionPane.showMessageDialog(null,"Selecione uma data a ser excluida");
        }
        readJTable();
    }//GEN-LAST:event_btnExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameTwo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameTwo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameTwo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameTwo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameTwo().setVisible(true);
            }
        });
    }
    
    public void readJTable(){
        DefaultTableModel modelo = (DefaultTableModel) jtbFrameTwo.getModel();
        modelo.setNumRows(0);
        FechamentoDAO fdao = new FechamentoDAO();
        
        for(Fechamento f : fdao.read()){
            
            modelo.addRow(new Object[]{
                f.getId(),
                f.getData(),
                f.getSobra()
            });
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton btnApFechado;
    private javax.swing.JButton btnApView;
    private javax.swing.JButton btnCAtFechado;
    private javax.swing.JButton btnCAtView;
    private javax.swing.JButton btnCRtFechado;
    private javax.swing.JButton btnCRtView;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnCarFechado;
    private javax.swing.JButton btnCarView;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnRecFechado;
    private javax.swing.JButton btnRecView;
    private javax.swing.JButton btnSaiFechado;
    private javax.swing.JButton btnSaiView;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVenFechado;
    private javax.swing.JButton btnVenView;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtbFrameTwo;
    private javax.swing.JLabel lblAprazo;
    private javax.swing.JLabel lblCaixaAnterior;
    private javax.swing.JLabel lblCaixaAtual;
    private javax.swing.JLabel lblCartao;
    private javax.swing.JLabel lblRecebido;
    private javax.swing.JLabel lblSaida;
    private javax.swing.JLabel lblSobra;
    private javax.swing.JLabel lblVendas;
    private javax.swing.JTextField txtAprazo;
    private javax.swing.JTextField txtCaixaAnterior;
    private javax.swing.JTextField txtCaixaAtual;
    private javax.swing.JTextField txtCartao;
    private javax.swing.JTextField txtRecebido;
    private javax.swing.JTextField txtSaida;
    private javax.swing.JTextField txtVendas;
    // End of variables declaration//GEN-END:variables
}
