/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author lucas
 */
public class FrameOne extends javax.swing.JFrame {

    /**
     * Creates new form FrameOne
     */
    public FrameOne() {
        initComponents();
        setSize(1100,600);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtbUsuario = new javax.swing.JButton();
        jtbUsuario1 = new javax.swing.JButton();
        jtbUsuario2 = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1100, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        jtbUsuario.setBackground(new java.awt.Color(61, 91, 129));
        jtbUsuario.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jtbUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconUsuario.png"))); // NOI18N
        jtbUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jtbUsuario);
        jtbUsuario.setBounds(330, 330, 420, 180);

        jtbUsuario1.setBackground(new java.awt.Color(61, 91, 129));
        jtbUsuario1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jtbUsuario1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/RelatorioIcon.png"))); // NOI18N
        jtbUsuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbUsuario1ActionPerformed(evt);
            }
        });
        getContentPane().add(jtbUsuario1);
        jtbUsuario1.setBounds(560, 90, 420, 180);

        jtbUsuario2.setBackground(new java.awt.Color(61, 91, 129));
        jtbUsuario2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jtbUsuario2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconeCalc.png"))); // NOI18N
        jtbUsuario2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbUsuario2ActionPerformed(evt);
            }
        });
        getContentPane().add(jtbUsuario2);
        jtbUsuario2.setBounds(100, 90, 420, 180);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/background default.png"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, -40, 1080, 640);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtbUsuario2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbUsuario2ActionPerformed
        // TODO add your handling code here:
        new FrameTwo().setVisible(true);
    }//GEN-LAST:event_jtbUsuario2ActionPerformed

    private void jtbUsuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbUsuario1ActionPerformed
        // TODO add your handling code here:
        new FrameThree().setVisible(true);
    }//GEN-LAST:event_jtbUsuario1ActionPerformed

    private void jtbUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbUsuarioActionPerformed
        // TODO add your handling code here:
        new FrameFour().setVisible(true);
    }//GEN-LAST:event_jtbUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameOne().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton jtbUsuario;
    private javax.swing.JButton jtbUsuario1;
    private javax.swing.JButton jtbUsuario2;
    // End of variables declaration//GEN-END:variables
}
